### ISSUE TITLE
Event alias deprecated since jQuery 1.8

### ISSUE THREAD

**Issue by hookdesignalter** [scubafly/Scroll-to-destination-anchors#2]
Module not working on D8.4 - 

In the scroll_to_destination_anchors.js file on line 12 you have

$(window).load(function()

These event aliases have been deprecated - changing it to 

$(window).on('load', function()

solves the issue and the module works properly again.

**Comment by scubafly** [comment]
Thanks for reporting this issue. Can you confirm it is working now?

**Comment by hookdesignalter** [comment]
Thanks @scubafly - can confirm patched version works.

**Comment by scubafly** [comment]
Wow that was a quick response 🥇 :) Thank you for testing.
